const teachers = [
    { abbr: "高子", full: "高冬梅", desc: "语文老师" },
    { abbr: "叶子", full: "叶枫", desc: "数学老师" },
    { abbr: "余子", full: "余丹丹", desc: "英语老师" },
    { abbr: "邓子", full: "邓婉晴", desc: "历史老师" },
    { abbr: "宁子", full: "宁明惠", desc: "道法老师", time: "六年级、七年级下" },
    { abbr: "殷子", full: "殷新", desc: "道法老师", time: "八年级起" },
    { abbr: "许子", full: "许妍", desc: "地理老师", time: "八年级起" },
    { abbr: "孙子", full: "孙惠敏", desc: "物理老师", time: "八年级起" },
    { abbr: "郎子", full: "郎润凯", desc: "劳技老师", time: "八年级起" },
    { abbr: "武子", full: "武烨", desc: "年级主任" },
    { abbr: "毕子", full: "毕建清", desc: "生物老师" },
    { abbr: "刘子", full: "刘奕凯", desc: "信息老师", time: "八年级起" },
    { abbr: "刘子二号", full: "刘苗芳", desc: "6班数学老师" },
    { abbr: "王子一号", full: "王继玲", desc: "道法老师", time: "七年级上" },
    { abbr: "王子二号", full: "王昱", desc: "体育老师", time: "七年级起" },
    { abbr: "陈子一号", full: "陈雯东", desc: "音乐老师"},
    { abbr: "陈子二号", full: "陈彪", desc: "3班数学老师（七下辞职）"},
    { abbr: "陈子三号", full: "陈玉玲", desc: "物理老师", time: "六、七年级" },
    { abbr: "范子一号", full: "范丽君", desc: "心理老师" },
    { abbr: "范子二号", full: "范道强", desc: "其他体育老师" },
    { abbr: "王校长", full: "王学军", desc: "校长" },
    // { abbr: "丁副校长", full: "丁？？", desc: "副校长" },
    { abbr: "欧阳子", full: "欧阳璟", desc: "某次公开课试讲英语老师" },
]

const students1 = [
    { 1: "陈子悦" }, { 2: "崔家康" }, { 3: "顾辰逊" }, { 4: "顾擎宇" }, { 5: "黄竞远" }, { 6: "康洲诚" }, { 9: "潘言嘉" },
    { 10: "邵黄裔" }, { 11: "王浡文" }, { 12: "王梓涵" }, { 13: "吴安辰" }, { 14: "吴佳谦" }, { 16: "张申熠" }, { 17: "张炜岷" },
    { 18: "郑博豪" }, { 19: "朱昱霖" }, { 20: "曹馨昀" }, { 21: "崔雯琳" }, { 22: "方霖悦" }, { 23: "冯馨冉" }, { 24: "顾依萱" },
    { 25: "何紫欣" }, { 26: "李怡然" }, { 27: "林明泽" }, { 28: "刘彦君" }, { 29: "钱奕昕" }, { 30: "乔睿菡" }, { 31: "宋悠然" },
    { 32: "隋宛桐" }, { 33: "夏铭月" }, { 34: "杨宸瑶" }, { 35: "郁宸婷" }, { 36: "张梦鎱" }, { 37: "隆逸辰" }, { 38: "胡蝶泉" },
]

const students2 = [
    { 1: "陈知行" }, { 2: "戴语骏" }, { 3: "丁梓杰" }, { 4: "顾益谦" }, { 5: "郭沐鑫" }, { 6: "何泰逸" }, { 7: "胡诚杰" },
    { 8: "黄嘉睿" }, { 9: "李沛霖" }, { 10: "施宝华" }, { 11: "谈宸铠" }, { 12: "王博嘉" }, { 13: "王冠程" }, { 14: "肖凡非" },
    { 15: "熊泽楷" }, { 16: "徐宸灏" }, { 17: "张轶善" }, { 18: "郑天星" }, { 19: "朱崇璟" }, { 20: "包晓妍" }, { 21: "柴雨轩" },
    { 22: "陈艺嘉" }, { 23: "都朔祎" }, { 24: "胡沐儒" }, { 25: "黄昕甜" }, { 26: "姜嘉悦" }, { 27: "雷舒雯" }, { 28: "李玥瑶" },
    { 29: "刘子晴" }, { 30: "潘若水" }, { 31: "施逸文" }, { 32: "王睿琪" }, { 33: "王馨恬" }, { 34: "王怡蓓" }, { 35: "严茹萱" },
    { 36: "严雨阳" }, { 37: "张嘉琦" },
]

// 按班级和学号取同学姓名，如 stu(2, 10) -> "施宝华"
const stu = (cls, num) => (cls === 1 ? students1 : students2).find(s => num in s)[num];
// 按简称取老师姓名，如 tea('叶子') -> "叶枫"
const tea = abbr => teachers.find(t => t.abbr === abbr).full;

const quotes = [
    // 第一册
    // 1
    { author: tea('高子'), content: `去你的，滚一边儿去`, tags: ["脏话"] },
    { author: tea('高子'), content: `神经病`, tags: ["脏话"] },
    { author: tea('高子'), content: `喵`, tags: ["动物世界"] },
    { author: tea('高子'), content: `求求你，要我命`, tags: ["暴言"] },
    { author: tea('高子'), content: `吃俺老高一棒`, tags: ["吃的"] },
    { author: tea('高子'), content: `再插话我就抽你`, tags: ["脏话", "班级纪律"] },
    { author: tea('高子'), content: `我在外面有很多私生子`, tags: ["日常"] },
    { author: tea('高子'), content: `你是2班的人吗？我咋不认识你。`, tags: ["日常"] },
    { author: tea('高子'), content: `我都气得想把你打死`, tags: ["脏话"] },
    { author: tea('高子'), content: `我刚才讲什么嘞？`, tags: ["日常"] },
    { author: tea('高子'), content: `脚尖朝地跳芭蕾`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 10)}我派你去殖民，${stu(2, 12)}我派你去探险`, tags: ["日常"] },
    { author: tea('高子'), content: `你存在的意义就是给我爽一下`, tags: ["开车"] },
    { author: tea('高子'), content: `你俩是男同吗？`, tags: ["开车"] },
    { author: tea('高子'), content: `我讲黄色笑话比你们有年龄优势。`, tags: ["开车"] },
    { author: tea('高子'), content: `想摸回家摸自己去`, tags: ["开车"] },
    { author: tea('高子'), content: `你们没在我头顶上看到一朵蘑菇云吗？`, tags: ["日常"] },
    { author: tea('高子'), content: `滚！全都给我滚蛋！`, tags: ["脏话"] },
    { author: tea('叶子'), content: `不要占着茅坑不拉屎`, tags: ["屎尿屁"] },
    // 2
    { author: tea('高子'), content: `你都说生孩子像拉屎一样了，那你是不是生过孩子？`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `${stu(2, 1)}说得对，再过十年男人都能生孩子了。`, tags: ["日常"] },
    { author: tea('高子'), content: `以后你们就去做家庭主夫，让女孩子出去赚钱`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 1)}你在干嘛？准备生孩子吗？`, tags: ["日常"] },
    { author: tea('高子'), content: `做母亲身体好的话孩子身体也会好，所以我支持男人生孩子，特别是像${stu(2, 1)}这样。${stu(2, 1)}你快去生一个小${stu(2, 1)}出来，你生了我还要抱一抱呢。`, tags: ["日常"] },
    { author: tea('高子'), content: `我支持你们想分就分，想合就合。`, tags: ["日常"] },
    { author: tea('高子'), content: `你干嘛呢，男人？你快回去吧，男人。是个名副其实的男人。没写完作业不算男人。`, tags: ["作业考试"] },
    { author: tea('高子'), content: `你肚子里没蛋，下得出来吗？`, tags: ["日常"] },
    { author: tea('高子'), content: `疯了吗？`, tags: ["日常"] },
    { author: tea('高子'), content: `像我这样彪悍蛮横的老太太捧人就特别恶心`, tags: ["日常"] },
    { author: tea('高子'), content: `我还以为他是讲大道理的枯燥说教者（孔子）`, tags: ["日常"] },
    { author: tea('高子'), content: `《论语》教育牛马做合格牛马`, tags: ["动物世界"] },
    { author: tea('高子'), content: `统治者最大的资源就是老百姓`, tags: ["日常"] },
    // 3
    { author: tea('高子'), content: `你是人吗？`, tags: ["日常"] },
    { author: tea('高子'), content: `他们那时候没避孕的方法`, tags: ["开车"] },
    { author: stu(2, 10), content: `他们就非得搞吗？`, tags: ["开车"] },
    { author: tea('高子'), content: `生我前一分钟还在做`, tags: ["开车"] },
    { author: tea('高子'), content: `我的报纸呢？↗我的报纸`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `然后六班的人就给我起一个外号，叫“棒棒糖哥哥”`, tags: ["日常"] },
    { author: tea('邓子'), content: `啊！`, tags: ["日常"] },
    { author: tea('邓子'), content: `屎`, tags: ["屎尿屁"] },
    { author: tea('邓子'), content: `你的陵墓修好了，你可以准备去死啦！`, tags: ["日常"] },
    { author: tea('邓子'), content: `我们换个高级点的说法`, tags: ["日常"] },
    { author: tea('邓子'), content: `照片上有迪丽热巴`, tags: ["日常"] },
    { author: tea('邓子'), content: `新加坡的鞭刑特别好啊，值得借鉴`, tags: ["日常"] },
    { author: tea('毕子'), content: `你们今天回去多泡一泡`, tags: ["日常"] },
    { author: tea('高子'), content: `鬼东西们就是搞笑`, tags: ["日常"] },
    { author: tea('叶子'), content: `像我这种死胖子`, tags: ["外貌身材"] },
    // 4
    { author: tea('余子'), content: `傻子`, tags: ["日常"] },
    { author: tea('余子'), content: `${stu(2, 15)}你是不是大脑有小脑的病`, tags: ["日常"] },
    { author: tea('余子'), content: `右边的左边，左边的右边，意思就是这个意思`, tags: ["日常"] },
    { author: tea('余子'), content: `你的imagination怎么也拼错了小雷雷`, tags: ["日常"] },
    { author: tea('余子'), content: `${stu(2, 21)}你废子`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `周杰伦唱歌都比你好听`, tags: ["名人梗"] },
    { author: tea('叶子'), content: `你要证明${tea('叶子')}是个男的，首先你要证明${tea('叶子')}是女的是错的，然后你还要证明${tea('叶子')}是不男不女也是错的`, tags: ["日常"] },
    { author: tea('叶子'), content: `我是地球人`, tags: ["日常"] },
    { author: tea('叶子'), content: `从此我的外号就是“浙江省希望杯三等奖差三分的人”`, tags: ["日常"] },
    { author: tea('叶子'), content: `现在我们来上历史课`, tags: ["日常"] },
    { author: tea('叶子'), content: `啊菩萨给我几十万`, tags: ["日常"] },
    { author: tea('叶子'), content: `啊 God`, tags: ["日常"] },
    { author: tea('叶子'), content: `你要搞死他`, tags: ["日常"] },
    { author: tea('叶子'), content: `我今天去菜场买菜，我买了橘子、白菜、猪肉，一共花了55元，然后回家问我爸，我橘子多少钱1斤`, tags: ["动物世界", "吃的"] },
    { author: tea('余子'), content: `以后你们的教室就在办公室`, tags: ["班级纪律"] },
    { author: tea('高子'), content: `除非我能变成孙悟空`, tags: ["名人梗"] },
    { author: tea('叶子'), content: `${stu(1, 9)}打篮球就是科比，唱歌就是陶喆，然后数学课站起来一脸茫然`, tags: ["学科", "名人梗", "班级纪律"] },
    // 5
    { author: tea('高子'), content: `哎呦，这个可难不倒我`, tags: ["日常"] },
    { author: tea('高子'), content: `我有聪明的学生，老师糊涂一点没关系`, tags: ["日常"] },
    { author: tea('高子'), content: `有点糊涂`, tags: ["日常"] },
    { author: tea('高子'), content: `你还有意见了嘞`, tags: ["日常"] },
    { author: tea('高子'), content: `□□□□□□□□□□□`, tags: ["日常"] },
    { author: tea('高子'), content: `余老师没资格给我开三联单`, tags: ["日常"] },
    { author: stu(2, 10), content: `哎呦${stu(2, 2)}，我真想艹死你`, tags: ["开车"] },
    { author: stu(2, 3), content: `余AA我要超市你`, tags: ["开车"] },
    { author: tea('范子一号'), content: `这个取名方式，网速很快啊`, tags: ["日常"] },
    { author: tea('高子'), content: `下次你就在拉裤子里`, tags: ["日常"] },
    { author: tea('许子'), content: `一直在发出什么奇怪的声音啊`, tags: ["日常"] },
    { author: tea('高子'), content: `把你们跟打鬼子一样赶走`, tags: ["日常"] },
    { author: tea('高子'), content: `那口香糖会疼的`, tags: ["日常"] },
    { author: tea('高子'), content: `弱智`, tags: ["日常"] },
    { author: tea('高子'), content: `有的“狗东西”是怜爱、溺爱`, tags: ["脏话", "动物世界"] },
    { author: tea('范子二号'), content: `啥呀`, tags: ["日常"] },
    { author: tea('高子'), content: `这是啥笔`, tags: ["日常"] },
    { author: tea('高子'), content: `傻人做傻笔`, tags: ["日常"] },
    { author: tea('余子'), content: `你的crush没忘吧`, tags: ["日常"] },
    { author: tea('余子'), content: `我不知道你把书保持这么干净干什么`, tags: ["日常"] },
    // 6
    { author: stu(1, 2), content: `我们都是主动上□的`, tags: ["日常"] },
    { author: tea('余子'), content: `啥主动被动这是固定搭配`, tags: ["日常"] },
    { author: tea('余子'), content: `你变性了是吧`, tags: ["日常"] },
    { author: tea('余子'), content: `谁再“唉”要被我砍成躁子了`, tags: ["日常"] },
    { author: tea('余子'), content: `是你用脚蹄子够不到的东西`, tags: ["日常"] },
    { author: tea('余子'), content: `到时候你□上厕所都在背啊`, tags: ["屎尿屁"] },
    { author: tea('余子'), content: `贱兮兮的`, tags: ["脏话"] },
    { author: tea('叶子'), content: `我们的宇宙是扭曲的`, tags: ["日常"] },
    { author: tea('叶子'), content: `这里出现了一个预言家，他预言了200年后发生的事情`, tags: ["吹牛"] },
    { author: tea('叶子'), content: `你回家打开一个本子，写100条预言，其中只要有3条中了，你就是预言家`, tags: ["吹牛"] },
    { author: tea('叶子'), content: `我微积分大学没过，后来重修过的，我24岁时还在大学里重修高等数学`, tags: ["学科"] },
    { author: tea('叶子'), content: `我可真牛逼，我自己编的这个题在100年后就是《九章算术》`, tags: ["吹牛", "名人梗", "动物世界"] },
    { author: tea('叶子'), content: `我这个人呢，不太善于表达`, tags: ["日常"] },
    { author: tea('叶子'), content: `我能骂你五分钟不重样`, tags: ["日常"] },
    { author: tea('叶子'), content: `我看${stu(2, 3)}是挺帅的`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `简直是折我的寿`, tags: ["日常"] },
    // 7
    { author: tea('高子'), content: `这可是我们好几个老师公认的帅哥`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `还好还有大帅哥`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `${stu(2, 21)}娇（羞）滴滴的`, tags: ["日常"] },
    { author: tea('高子'), content: `想着你的□□□□`, tags: ["日常"] },
    { author: tea('余子'), content: `□□□□□□□□□□□□`, tags: ["日常"] },
    { author: tea('余子'), content: `（伸颈瞪眼）啊`, tags: ["日常"] },
    { author: tea('余子'), content: `（耸肩）棒棒哒啥情况`, tags: ["日常"] },
    { author: tea('余子'), content: `你脑残`, tags: ["日常"] },
    { author: tea('余子'), content: `你是个什么东西`, tags: ["日常"] },
    { author: tea('叶子'), content: `活字印刷术这个技术牛逼不牛逼`, tags: ["吹牛", "动物世界"] },
    { author: tea('叶子'), content: `我老师就被我爸妈骂`, tags: ["日常"] },
    { author: tea('叶子'), content: `移动公司是六毛一分钟，联通公司是五毛五一分钟（因为10点前根本打不通）`, tags: ["日常"] },
    { author: tea('叶子'), content: `我一个联通的兄弟在打牌的时候跟一个移动的兄弟打，用五毛五跟六毛的拼了!`, tags: ["日常"] },
    { author: tea('叶子'), content: `其实我也想请病假，没人拦着，但有钱拦着`, tags: ["日常"] },
    { author: tea('叶子'), content: `我要是有钱也不至于遇到你`, tags: ["日常"] },
    { author: tea('叶子'), content: `我下家没地，我不是地主`, tags: ["日常"] },
    { author: tea('叶子'), content: `以你的智商我很难跟你解释`, tags: ["日常"] },
    { author: tea('叶子'), content: `这11题我们就不理它啦`, tags: ["日常"] },
    // 8
    { author: tea('叶子'), content: `人生最大的悲剧是钱没花掉人没了`, tags: ["日常"] },
    { author: tea('叶子'), content: `你再把门□□起来我把门拆掉`, tags: ["日常"] },
    { author: tea('叶子'), content: `我女儿已经在家躺了两天了，发烧40℃都超过了`, tags: ["日常"] },
    { author: stu(1, 30), content: `□了没`, tags: ["日常"] },
    { author: tea('叶子'), content: `□□□□那么一张擦屁股纸`, tags: ["开车", "屎尿屁"] },
    { author: tea('高子'), content: `我绕着学校跑，我的班主任追着我打`, tags: ["日常"] },
    { author: tea('高子'), content: `所以被我叉了`, tags: ["脏话"] },
    { author: tea('高子'), content: `在这里插入`, tags: ["日常"] },
    { author: tea('高子'), content: `女高婉转`, tags: ["日常"] },
    { author: tea('高子'), content: `出了点罢个（bug）`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `我觉得呢冬天就不应该上学`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `这首歌（友谊长）听过没有，我们一起唱一遍好不好`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `我来给大家领唱`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `这主席一生气我好怕怕呀`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `这三四班的同学被我培养得非常正直，这朱思杰，是带头骂我这个三班班主任`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `（在）抖音刷美女`, tags: ["外貌身材"] },
    { author: tea('陈子二号'), content: `我一般呢还是温柔一点`, tags: ["日常"] },
    // 9
    { author: tea('余子'), content: `下你个大头`, tags: ["日常"] },
    { author: tea('余子'), content: `你的小耳朵听不见`, tags: ["日常"] },
    { author: tea('范子二号'), content: `压儿一（一二一）`, tags: ["日常"] },
    { author: tea('余子'), content: `□□□□□□□□□□擦屁股纸`, tags: ["开车", "屎尿屁"] },
    { author: tea('余子'), content: `□□□□□□□□□□□□□□□□`, tags: ["日常"] },
    { author: tea('余子'), content: `你怎么□得要死不活的`, tags: ["日常"] },
    { author: tea('余子'), content: `你这熊脑子不是人脑子是吧`, tags: ["日常"] },
    { author: tea('余子'), content: `动物也是个人`, tags: ["日常"] },
    { author: tea('余子'), content: `我今天叫你叫${stu(2, 2)}二号`, tags: ["日常"] },
    { author: tea('余子'), content: `谁是${stu(2, 2)}三号`, tags: ["日常"] },
    { author: tea('余子'), content: `温柔的一笑`, tags: ["日常"] },
    { author: tea('余子'), content: `其他同学都快憋出内伤了`, tags: ["日常"] },
    { author: tea('余子'), content: `你个傻子×2`, tags: ["日常"] },
    { author: tea('刘子'), content: `这节课还蛮(mān)难的啊`, tags: ["日常"] },
    { author: tea('毕子'), content: `然后插进去`, tags: ["日常"] },
    { author: tea('毕子'), content: `切切切切切切切`, tags: ["日常"] },
    { author: tea('高子'), content: `你飞一个给我看看`, tags: ["日常"] },
    { author: tea('邓子'), content: `小小年纪就一把年纪`, tags: ["日常"] },
    { author: tea('邓子'), content: `比我妈还关心别人的人生大事`, tags: ["日常"] },
    // 10
    { author: tea('邓子'), content: `东西夹击把他给灭了`, tags: ["日常"] },
    { author: tea('邓子'), content: `一起把宗教传进来`, tags: ["日常"] },
    { author: tea('高子'), content: `你是城巴佬`, tags: ["日常"] },
    { author: tea('高子'), content: `这个“秃”是“禾”下加一个“几”吧`, tags: ["日常"] },
    { author: tea('高子'), content: `□□□□□□`, tags: ["日常"] },
    { author: tea('高子'), content: `□□□□□□□□□`, tags: ["日常"] },
    { author: tea('高子'), content: `你继续给我站着，这个前面吃同学的男生`, tags: ["吃的"] },
    { author: tea('高子'), content: `咿呀他终于请假了`, tags: ["日常"] },
    { author: tea('邓子'), content: `千万不要当老师`, tags: ["日常"] },
    { author: tea('余子'), content: `看完大家都想去取经了`, tags: ["日常"] },
    { author: tea('高子'), content: `分数650到700……吧`, tags: ["作业考试"] },
    { author: "钱子", content: `外国人能搞的怎么中国人不能搞`, tags: ["日常"] },
    { author: tea('王子一号'), content: `我也不想重新做人`, tags: ["日常"] },
    { author: "□□□", content: `□虚空，□□又虚又空`, tags: ["日常"] },
    { author: tea('高子'), content: `放在谦谦手里`, tags: ["日常"] },
    { author: tea('邓子'), content: `你们对资本家的心理一无所知`, tags: ["日常"] },
    { author: tea('邓子'), content: `我还要在这里混呢`, tags: ["日常"] },
    { author: tea('邓子'), content: `这很麻烦的`, tags: ["日常"] },
    { author: tea('邓子'), content: `我教的第一届学生还给我画大饼呢`, tags: ["日常"] },
    // 11
    { author: tea('邓子'), content: `马上都要穿越了`, tags: ["网络梗"] },
    { author: tea('邓子'), content: `都(dū)老师……啊□`, tags: ["日常"] },
    { author: tea('邓子'), content: `哎哟哪□□好`, tags: ["日常"] },
    { author: tea('邓子'), content: `等于□□□□□□□扇你`, tags: ["日常"] },
    { author: tea('邓子'), content: `你叹气叹□吧`, tags: ["日常"] },
    { author: tea('邓子'), content: `□□□□□□□□□□□□□□`, tags: ["日常"] },
    { author: tea('邓子'), content: `能□□□健康的□□`, tags: ["日常"] },
    { author: tea('叶子'), content: `被一个原子弹炸和被两个原子弹炸是一样的`, tags: ["日常"] },
    { author: tea('叶子'), content: `还他妈屁事都没有`, tags: ["屎尿屁"] },
    { author: tea('叶子'), content: `天天下课在那里晃来晃去晃来晃去`, tags: ["日常"] },
    { author: tea('叶子'), content: `你写个格式装一下`, tags: ["日常"] },
    { author: tea('叶子'), content: `每次我进到这个教室里就愁眉苦脸的`, tags: ["班级纪律"] },
    { author: tea('叶子'), content: `我要开始变戏法了噢`, tags: ["日常"] },
    { author: tea('余子'), content: `${stu(2, 7)}，你给我屎起来`, tags: ["屎尿屁"] },
    { author: tea('叶子'), content: `操你妈`, tags: ["脏话"] },
    { author: tea('叶子'), content: `他娘的`, tags: ["脏话"] },
    { author: tea('余子'), content: `死过来`, tags: ["日常"] },
    { author: stu(2, 18), content: `好疼啊`, tags: ["日常"] },
    { author: stu(2, 18), content: `别压我`, tags: ["日常"] },
    // 12
    { author: tea('高子'), content: `马上他（${tea('叶子')}）就像一个战斗机一样过来`, tags: ["日常"] },
    { author: tea('高子'), content: `遗留的${stu(2, 37)}`, tags: ["日常"] },
    { author: tea('高子'), content: `把四只脚都举起来`, tags: ["日常"] },
    { author: tea('陈子二号'), content: `蔡老师就只会让我滚`, tags: ["脏话"] },
    { author: tea('陈子二号'), content: `□□调戏老师`, tags: ["日常"] },
    { author: tea('叶子'), content: `我刚当老师时□□□□□□□学生`, tags: ["日常"] },
    { author: tea('叶子'), content: `你不要再抱有幻想了`, tags: ["日常"] },
    { author: tea('余子'), content: `不要乱□□□□`, tags: ["日常"] },
    { author: tea('余子'), content: `你在说□□□□□也笑`, tags: ["日常"] },
    { author: tea('余子'), content: `□□□还是不是人`, tags: ["日常"] },
    { author: tea('毕子'), content: `临时加一个提问环节`, tags: ["日常"] },
    { author: tea('毕子'), content: `来，记吧`, tags: ["日常"] },
    { author: tea('毕子'), content: `你是牙膏我是挤吗`, tags: ["日常"] },
    { author: tea('高子'), content: `没实力就稀烂一坨屎`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `这不废物吗`, tags: ["日常"] },
    { author: tea('高子'), content: `你怎么这么□（让猪八戒来睡你！）`, tags: ["动物世界", "开车"] },
    { author: tea('高子'), content: `历史不就是史吗`, tags: ["日常"] },
    { author: tea('邓子'), content: `不要玩烂梗`, tags: ["日常"] },
    // 13
    { author: tea('邓子'), content: `你们□□□看一些不干不净的东西。`, tags: ["日常"] },
    { author: tea('邓子'), content: `双男主？`, tags: ["日常"] },
    { author: tea('邓子'), content: `我上学时□看小说：“造纸术真是伟大的发明”，做作业时：“真□□□□□□”`, tags: ["作业考试"] },
    { author: tea('邓子'), content: `你□□□□□□□□□□□□□`, tags: ["日常"] },
    { author: tea('邓子'), content: `当时这个射精（一说为《圣经》）的控制权`, tags: ["日常"] },
    { author: tea('邓子'), content: `我前两天看到一个特别阴的短视频`, tags: ["日常"] },
    { author: tea('邓子'), content: `傻孩子，你怎么会是傻孩子呢`, tags: ["日常"] },
    { author: tea('高子'), content: `你今天就在新竹园打地铺吧`, tags: ["日常"] },
    { author: tea('高子'), content: `我把你们家底都翻过了`, tags: ["日常"] },
    { author: tea('高子'), content: `好色不一定是缺点，不好色怎么繁衍后代呢？你难道不喜欢帅哥美女吗？虚伪。我反正喜欢看帅哥美女。${stu(2, 10)}你想让我喜欢你，你就变美一点。`, tags: ["外貌身材"] },
    { author: stu(2, 7), content: `孙行者都是拉拉`, tags: ["开车", "名人梗"] },
    { author: tea('高子'), content: `底部的同学做得跟屎一样`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `你们烂就烂吧`, tags: ["日常"] },
    { author: tea('王子一号'), content: `我从幼儿园到八年级从来没有写过作业（道法）`, tags: ["作业考试"] },
    // 14
    { author: tea('王子一号'), content: `这个老头不一般`, tags: ["日常"] },
    { author: tea('王子一号'), content: `电话是管控不了我的`, tags: ["日常"] },
    { author: tea('王子一号'), content: `你长得很像《海贼王》里一个角色，橙汁`, tags: ["日常"] },
    { author: tea('王子一号'), content: `是你们都喜欢的类型吗`, tags: ["日常"] },
    { author: tea('王子一号'), content: `来，刚刚在抠鼻屎的${stu(2, 18)}，你来`, tags: ["屎尿屁"] },
    { author: tea('王子一号'), content: `你们两个男生怎么搞得跟变态一样`, tags: ["日常"] },
    { author: tea('王子一号'), content: `要不要拿个□□□把你那两根卷毛给卷直了`, tags: ["日常"] },
    { author: tea('高子'), content: `你是猪吗？`, tags: ["动物世界"] },
    { author: tea('高子'), content: `见证奇迹的时刻到了`, tags: ["日常"] },
    { author: tea('高子'), content: `我生气了`, tags: ["日常"] },
    { author: tea('高子'), content: `大家掌声欢迎都老师`, tags: ["日常"] },
    { author: tea('高子'), content: `想得美！（${stu(2, 24)}）嫁给你？`, tags: ["日常"] },
    { author: tea('高子'), content: `你嫁入豪门说不定只是变成生育机器`, tags: ["日常"] },
    { author: tea('高子'), content: `我觉得很好玩`, tags: ["日常"] },
    { author: tea('高子'), content: `你（${stu(2, 7)}）真够妩媚的`, tags: ["日常"] },
    { author: tea('邓子'), content: `有点高级`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `对我来说，语文是一个很诡异的学科。`, tags: ["日常"] },
    // 15
    { author: tea('叶子'), content: `你不把我当人看咯，我也是同学呀`, tags: ["日常"] },
    { author: tea('叶子'), content: `上课上着上着边变态怖片啦`, tags: ["班级纪律"] },
    { author: tea('高子'), content: `咿↗↗↗~`, tags: ["日常"] },
    { author: tea('高子'), content: `鸡皮疙瘩都掉地上了`, tags: ["动物世界"] },
    { author: tea('高子'), content: `你卧倒干什么，□□没有敌人、没有炸弹`, tags: ["日常"] },
    { author: tea('高子'), content: `唉养个儿子不错`, tags: ["日常"] },
    { author: tea('高子'), content: `真好，有你们真好`, tags: ["日常"] },
    { author: tea('高子'), content: `你就是个资本家，今天我们一起去他家吃大户啊`, tags: ["吃的"] },
    { author: stu(2, 18), content: `□□不可以`, tags: ["日常"] },
    { author: stu(2, 19), content: `不行`, tags: ["日常"] },
    { author: tea('余子'), content: `奇葩`, tags: ["日常"] },
    { author: tea('余子'), content: `又有很多男同学的眼睛变成三角形的了啊`, tags: ["日常"] },
    { author: tea('余子'), content: `你写了个比□都会给分的`, tags: ["日常"] },
    { author: tea('余子'), content: `你要是能在原文找到答案，那出题的就是个傻子。`, tags: ["日常"] },
    { author: tea('范子一号'), content: `□种时候不许阳光开朗啊`, tags: ["日常"] },
    { author: tea('范子一号'), content: `呲着个大牙乐`, tags: ["日常"] },
    { author: tea('高子'), content: `你们俩隔空对骂`, tags: ["日常"] },
    { author: tea('余子'), content: `他要跳河了`, tags: ["日常"] },
    { author: tea('余子'), content: `你们这咋有两个非洲大峡谷啊`, tags: ["日常"] },
    // 16
    { author: tea('叶子'), content: `我们就听着你的声音波浪形地旋转`, tags: ["日常"] },
    { author: tea('叶子'), content: `什么个情况你们两个人分手啦`, tags: ["感情八卦"] },
    { author: tea('叶子'), content: `□□□□□□□□`, tags: ["日常"] },
    { author: tea('叶子'), content: `一见钟情□□□□`, tags: ["日常"] },
    { author: tea('叶子'), content: `你□□□□□□一样`, tags: ["日常"] },
    { author: tea('高子'), content: `□□□□叫`, tags: ["日常"] },
    { author: tea('高子'), content: `谁的屁股那么重`, tags: ["开车", "屎尿屁"] },
    { author: tea('高子'), content: `有些同学我还没查，等会我来查一下`, tags: ["日常"] },
    { author: tea('高子'), content: `谁的嘴巴便秘了呀，便秘了要去医院看的`, tags: ["日常"] },
    { author: tea('高子'), content: `又不便秘为啥记作业这么慢`, tags: ["作业考试"] },
    { author: tea('高子'), content: `笑的人便秘啦`, tags: ["日常"] },
    { author: tea('高子'), content: `我又不是男生我为啥追你（${stu(2, 24)}）`, tags: ["日常"] },
    { author: tea('高子'), content: `你不喜欢我那我喜欢你啊`, tags: ["日常"] },
    { author: tea('高子'), content: `追不上你，那我就为了索爱奔赴山海行不行`, tags: ["网络梗"] },
    { author: tea('余子'), content: `就是□□滚`, tags: ["脏话"] },
    { author: tea('余子'), content: `给你个抱抱？`, tags: ["日常"] },
    { author: tea('余子'), content: `这默写本咋忽然变得这么大，变大灰啦`, tags: ["作业考试"] },
    { author: tea('叶子'), content: `它（新定义类型题目）取个什么阿猫阿狗你不管`, tags: ["动物世界"] },
    // 17
    { author: tea('叶子'), content: `他满分没有，菜鸡`, tags: ["动物世界", "吃的"] },
    { author: tea('叶子'), content: `这个教书真的一点味道都没有`, tags: ["日常"] },
    { author: tea('叶子'), content: `小嘴整天叭叭叭叭啦，不知道自己有多牛逼`, tags: ["吹牛", "动物世界"] },
    { author: tea('叶子'), content: `就拿个面包在那里搓搓搓`, tags: ["日常"] },
    { author: tea('毕子'), content: `你要不趴下睡吧`, tags: ["日常"] },
    { author: tea('叶子'), content: `老师也不是什么人`, tags: ["日常"] },
    { author: tea('叶子'), content: `少人不可怕，多人才可怕`, tags: ["日常"] },
    { author: tea('毕子'), content: `陶行知（${stu(2, 1)}）同学`, tags: ["日常"] },
    { author: tea('范子一号'), content: `这位孩儿`, tags: ["日常"] },
    { author: tea('范子一号'), content: `这位小帅`, tags: ["外貌身材"] },
    { author: tea('范子一号'), content: `这位小美`, tags: ["日常"] },
    { author: tea('毕子'), content: `你看你优秀的同桌`, tags: ["日常"] },
    { author: stu(2, 23), content: `同桌你该不会91看多了吧`, tags: ["日常"] },
    { author: tea('高子'), content: `哎哟喂，这感情深得嘞`, tags: ["日常"] },
    { author: tea('高子'), content: `活该`, tags: ["日常"] },
    { author: tea('范子一号'), content: `我来得不巧了`, tags: ["日常"] },
    { author: tea('刘子'), content: `他的耳朵打八折啦`, tags: ["日常"] },
    // 18
    { author: tea('高子'), content: `呆子`, tags: ["日常"] },
    { author: tea('高子'), content: `没死吧`, tags: ["暴言"] },
    { author: tea('高子'), content: `你上课又揍他`, tags: ["班级纪律"] },
    { author: tea('高子'), content: `为什么揍后面是妹不是哥呢？`, tags: ["日常"] },
    { author: tea('高子'), content: `我在你身上看到了大男子主义。`, tags: ["日常"] },
    { author: tea('高子'), content: `不要想多了。`, tags: ["日常"] },
    { author: tea('高子'), content: `你说你是傻逼。`, tags: ["脏话"] },
    { author: tea('高子'), content: `别笑了，傻子们`, tags: ["日常"] },
    { author: tea('高子'), content: `你再把我惹毛了我就把你烤成肉吃了`, tags: ["吃的"] },
    { author: tea('高子'), content: `我也不怕你回踹`, tags: ["日常"] },
    { author: tea('高子'), content: `顶多智商跟我差不多`, tags: ["日常"] },
    { author: tea('高子'), content: `来了个更低的`, tags: ["日常"] },
    { author: tea('高子'), content: `怎么样 更低吗 更高一点`, tags: ["日常"] },
    { author: tea('高子'), content: `受着`, tags: ["日常"] },
    { author: tea('邓子'), content: `顶不上来`, tags: ["日常"] },
    { author: tea('邓子'), content: `什么垃圾政权`, tags: ["日常"] },
    { author: tea('高子'), content: `干什么？你（${stu(2, 12)}）看片(piàn)？怪不得学习没精神。怪不得你每天帅帅的。你是不是看了？`, tags: ["外貌身材", "开车"] },
    // 19
    { author: tea('毕子'), content: `干什mó？`, tags: ["日常"] },
    { author: tea('毕子'), content: `为什么鸡腿好吃？`, tags: ["动物世界", "吃的"] },
    { author: tea('高子'), content: `插到底`, tags: ["开车"] },
    { author: "□□", content: `猪把食物分给我`, tags: ["动物世界"] },
    { author: tea('王子一号'), content: `算了，我不能爆粗口`, tags: ["日常"] },
    { author: tea('王子一号'), content: `这是1+1=2`, tags: ["日常"] },
    { author: tea('王子一号'), content: `我感觉你们是不管别人问你们有没有吃饭还是有没有什么爱好，你们的统一回答都是“我要上厕所”`, tags: ["屎尿屁", "吃的"] },
    { author: tea('王子一号'), content: `我们不需要BGM`, tags: ["日常"] },
    { author: tea('高子'), content: `雷大将`, tags: ["日常"] },
    { author: stu(2, 21), content: `为rar（啥是）我呀`, tags: ["日常"] },
    { author: tea('邓子'), content: `掌握了一个犯法的技术啊`, tags: ["日常"] },
    { author: tea('邓子'), content: `看看跟假币一样`, tags: ["日常"] },
    { author: tea('邓子'), content: `我要说句很关键的话：“玩手机玩的”`, tags: ["日常"] },
    { author: tea('邓子'), content: `都称呼自己为碳基生物`, tags: ["日常"] },
    { author: tea('邓子'), content: `天天教你就业的□有个屁用`, tags: ["屎尿屁"] },
    { author: tea('叶子'), content: `邵黄懿你又是一张擦屁股纸`, tags: ["开车", "屎尿屁"] },
    { author: tea('叶子'), content: `你妈是有脑子的`, tags: ["日常"] },
    // 20
    { author: tea('范子一号'), content: `你们班真是很诡异。`, tags: ["日常"] },
    { author: tea('高子'), content: `马上我来撸你。`, tags: ["开车"] },
    { author: tea('高子'), content: `把你当暖手宝撸你`, tags: ["开车"] },
    { author: tea('高子'), content: `看你有多千娇百媚。`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `你上来给大家抛一个（媚眼）试试`, tags: ["日常"] },
    { author: tea('高子'), content: `你要想称霸二班，要先踏过我的尸体。`, tags: ["日常"] },
    { author: tea('高子'), content: `想霸凌同学的话先跟我过过招。`, tags: ["日常"] },
    { author: tea('高子'), content: `我要把你训练成一个负责任的男人，将来对某个女孩子负责任`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 12)}你是不是看上${stu(2, 1)}了？`, tags: ["感情八卦"] },
    { author: tea('高子'), content: `你还知道自己□啊`, tags: ["日常"] },
    { author: tea('叶子'), content: `每次开学的时候豪情壮志，资料买个一本两本，然后每次期末的时候在闲鱼上面卖掉`, tags: ["作业考试"] },
    { author: tea('高子'), content: `爽不爽？舒服不？`, tags: ["开车"] },
    { author: tea('邓子'), content: `低于25分给你告到联合国去`, tags: ["日常"] },
    { author: tea('邓子'), content: `□□死了算了`, tags: ["日常"] },
    




    // 第二册
    // 1
    { author: tea('高子'), content: `某年某月某日，某人在小花园里落水。`, tags: ["日常"] },
    { author: tea('邓子'), content: `假若你参加科举考试，你就能得到BOSS直聘：皇帝严选。那${stu(2, 8)}同学就能当大官儿了。`, tags: ["作业考试"] },
    { author: tea('邓子'), content: `你重生，重生到了隋炀帝出生那一年`, tags: ["网络梗"] },
    { author: tea('邓子'), content: `我们用一些高大上、优美的词`, tags: ["日常"] },
    { author: tea('高子'), content: `谁是拉拉呀`, tags: ["开车"] },
    { author: tea('叶子'), content: `毕加索你慢一点`, tags: ["日常"] },
    { author: tea('高子'), content: `喏喏喏`, tags: ["日常"] },
    { author: tea('高子'), content: `强者就可以吃别人`, tags: ["吃的"] },
    { author: tea('高子'), content: `干啥 谁想吃我`, tags: ["吃的"] },
    { author: tea('高子'), content: `我是钢铁侠`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 1)}，你那么优秀`, tags: ["日常"] },
    { author: tea('邓子'), content: `嘻嘻`, tags: ["日常"] },
    { author: tea('宁子'), content: `你屁股下面有开关`, tags: ["开车", "屎尿屁"] },
    // 2
    { author: tea('邓子'), content: `${stu(2, 1)}或许真的有点姿色，但是性格太恶劣了。`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 6)}${stu(2, 12)}时不时眼神交流，你俩是Gay吗，眼神都能拉丝，我就这么意味深长地看着你们，你说你这么好，我就这么含情脉脉地看着你`, tags: ["开车", "班级纪律"] },
    { author: tea('许子'), content: `${stu(2, 10)}你上课用屁股听课吗？你屁股上长眼睛啦？你屁股上的眼睛是用来看的吗？`, tags: ["开车", "屎尿屁", "班级纪律"] },
    { author: tea('高子'), content: `gay是什么？……我十年前就知道了，其实在中国古代就有，gay的历史很悠久，至于拉拉我倒是没有看过。……拉拉在法国一起租房国家有补贴的`, tags: ["开车"] },
    // 3
    { author: tea('高子'), content: `我就不跟你又拉又gay`, tags: ["开车"] },
    { author: tea('叶子'), content: `现在${stu(1, 9)}是我的榜一大哥`, tags: ["日常"] },
    { author: tea('叶子'), content: `如果我捐一坨屎你也拍吗`, tags: ["屎尿屁"] },
    { author: tea('叶子'), content: `有没有同学有塑料袋，我要吐了`, tags: ["日常"] },
    { author: tea('高子'), content: `哪个你想跟个男的成亲也不容易`, tags: ["日常"] },
    { author: tea('高子'), content: `你是初牲`, tags: ["日常"] },
    { author: tea('高子'), content: `笑得花枝乱颤的`, tags: ["日常"] },
    { author: tea('高子'), content: `这个字什么个狗字啊`, tags: ["动物世界"] },
    { author: tea('邓子'), content: `这个人都已经死了怎么还诈尸呢`, tags: ["日常"] },
    { author: tea('高子'), content: `以后我遇到你（${stu(2, 1)}）合适的，我介绍给你`, tags: ["感情八卦"] },
    { author: tea('高子'), content: `（唱歌）天青色等烟雨，而我在等你……炊烟袅袅升起，隔江千万里。`, tags: ["日常"] },
    // 4
    { author: tea('高子'), content: `也不是不行，可以做拉拉，你要祈祷公主也是个拉`, tags: ["开车"] },
    { author: tea('高子'), content: `你想犯错。`, tags: ["日常"] },
    { author: tea('叶子'), content: `他说他是陶喆我都要吐了`, tags: ["名人梗"] },
    { author: tea('叶子'), content: `两个男同学上课手还拉着真是恶心。`, tags: ["开车", "班级纪律"] },
    { author: tea('高子'), content: `一天到晚阴得像蛋一样。`, tags: ["日常"] },
    { author: tea('叶子'), content: `武功秘籍传给你嗷`, tags: ["日常"] },
    { author: tea('叶子'), content: `我把尺卖了那我就成了无尺之徒`, tags: ["日常"] },
    { author: tea('叶子'), content: `这个尺里有魔法下次肯定能考好`, tags: ["日常"] },
    { author: tea('叶子'), content: `我黄浦江边上买房子去喽`, tags: ["日常"] },
    { author: tea('叶子'), content: `你们没有一个人能画到我心里去的`, tags: ["日常"] },
    // 5
    { author: tea('叶子'), content: `这个不是斗鸡眼就是帕金森`, tags: ["动物世界"] },
    { author: tea('高子'), content: `乌干达基巴来`, tags: ["日常"] },
    { author: tea('高子'), content: `讲黄段子我有年龄优势`, tags: ["开车"] },
    { author: tea('邓子'), content: `有这一个帅哥，我恨不得炫`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `搞事我真把你拉到前面来扒裤子展示。`, tags: ["开车"] },
    { author: tea('高子'), content: `滚一边去`, tags: ["脏话"] },
    { author: tea('邓子'), content: `多邻国比它（椰子精）猥琐多了`, tags: ["日常"] },
    { author: tea('余子'), content: `做你的脚`, tags: ["日常"] },
    { author: tea('高子'), content: `咋不看点带字的书`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `今天我长得像陶喆吗？`, tags: ["名人梗"] },
    { author: tea('陈子三号'), content: `诶！我鼻子上一个苍蝇屎`, tags: ["屎尿屁"] },
    // 6
    { author: tea('陈子三号'), content: `看得到你的爪子`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `${stu(1, 17)}你偷吃屎了这么开心`, tags: ["屎尿屁", "吃的"] },
    { author: tea('陈子三号'), content: `${stu(1, 17)}我跟你表达一下，我擅长表达`, tags: ["日常"] },
    { author: tea('叶子'), content: `笑嘻嘻你笑个der啊你`, tags: ["日常"] },
    { author: tea('叶子'), content: `这就是权力`, tags: ["日常"] },
    { author: tea('叶子'), content: `我的存款六位数字就可以了不用七位数。我死了以后天地银行烧给我`, tags: ["日常"] },
    { author: tea('高子'), content: `我年轻的时候可没那么菜哦`, tags: ["吃的"] },
    // 7
    { author: tea('高子'), content: `你们这帮小朋友真的怂得很啊`, tags: ["日常"] },
    { author: tea('叶子'), content: `怎么，屎拉不顺畅`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `你就是个狗人`, tags: ["动物世界"] },
    { author: tea('高子'), content: `一窝蛆一样`, tags: ["日常"] },
    { author: tea('高子'), content: `每天上课都拱来拱去 左边拱拱右边拱拱`, tags: ["班级纪律"] },
    { author: tea('高子'), content: `那你当女人啊，或者做男宠`, tags: ["开车"] },
    { author: tea('高子'), content: `你们这群人真是没法教`, tags: ["日常"] },
    { author: tea('高子'), content: `我看他（${stu(2, 1)}）又臭又硬`, tags: ["日常"] },
    { author: tea('高子'), content: `我今天怒了`, tags: ["日常"] },
    { author: tea('邓子'), content: `${stu(2, 10)}你怎么啦，抽大烟啦`, tags: ["日常"] },
    { author: tea('高子'), content: `这才像个男子汉`, tags: ["日常"] },
    // 8
    { author: tea('毕子'), content: `一天小苍蝇跟它妈妈在吃屎，小苍蝇问：“妈妈我们为何要吃这么恶心的食物”，它的妈妈说：“吃东西的时候不要说这么恶心的话”`, tags: ["屎尿屁", "吃的"] },
    { author: tea('高子'), content: `我是天下第一胖`, tags: ["日常"] },
    { author: tea('高子'), content: `少爷，回家去`, tags: ["日常"] },
    { author: tea('高子'), content: `把你的脑袋别到裤腰带上别紧`, tags: ["日常"] },
    { author: tea('高子'), content: `你就爱着明吧你`, tags: ["日常"] },
    { author: tea('邓子'), content: `你被撒旦附体啦！`, tags: ["日常"] },
    { author: tea('邓子'), content: `哇塞我家祖坟冒青烟啦，太棒了`, tags: ["日常"] },
    { author: tea('王子二号'), content: `要不是学校有明文规定，我早就帮你（${stu(2, 10)}）起飞了！`, tags: ["日常"] },
    // 9
    { author: tea('叶子'), content: `不要给我写这种傻屌结论噢`, tags: ["脏话"] },
    { author: tea('陈子三号'), content: `搭好就可以吗`, tags: ["日常"] },
    { author: tea('陈子一号'), content: `听你的！`, tags: ["日常"] },
    { author: tea('陈子一号'), content: `噢我好怕怕呀`, tags: ["日常"] },
    { author: tea('陈子一号'), content: `我们平民老百姓哪敢跟你作对啊`, tags: ["日常"] },
    { author: tea('陈子一号'), content: `我有一天玩植物大战僵尸把眼睛都玩瞎了第二天马上把它卸了`, tags: ["日常"] },
    { author: tea('叶子'), content: `像我这种老油条嘛`, tags: ["日常"] },
    { author: tea('余子'), content: `男生跟不上女生了`, tags: ["日常"] },
    { author: tea('高子'), content: `你不懂中国古代的文化就不要插插插……话`, tags: ["日常"] },
    { author: tea('高子'), content: `现在我成了个呆子喽`, tags: ["日常"] },
    { author: tea('高子'), content: `啊？柳如烟？？？`, tags: ["日常"] },
    { author: tea('高子'), content: `开启战斗模式！（双眼发光，上下蹦跳）`, tags: ["日常"] },
    { author: tea('高子'), content: `噢我这个书怎么拿反了呢？让我把书转360°（拿书转方向盘）`, tags: ["日常"] },
    // 10
    { author: tea('范子一号'), content: `你是奶龙啊`, tags: ["日常"] },
    { author: tea('高子'), content: `元芳你怎么看`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 1)}小宝`, tags: ["日常"] },
    { author: tea('叶子'), content: `如果全班36个都是${stu(1, 17)}的话那我已经在五楼天台了`, tags: ["日常"] },
    { author: tea('叶子'), content: `大家出生时都是两个肩膀扛一个脑袋`, tags: ["日常"] },
    { author: tea('高子'), content: `那还不如我来配乐，（咳咳）`, tags: ["日常"] },
    { author: tea('高子'), content: `我要做一只蟑螂`, tags: ["动物世界"] },
    { author: tea('邓子'), content: `哪一天特朗普给自己起个中文名`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `让你暑假的时候把A抄一万遍`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `${stu(1, 17)}是什么？superman！！！`, tags: ["日常"] },
    { author: tea('高子'), content: `你们刚才说了啥话？好文明啊再重复一遍`, tags: ["日常"] },
    { author: tea('叶子'), content: `左右看一看有没有傻屌错了`, tags: ["脏话"] },
    // 11
    { author: tea('叶子'), content: `你可以喷我脾气暴躁，但不能喷我对方向的把握`, tags: ["日常"] },
    { author: tea('叶子'), content: `${tea('叶子')}傻逼又在吹牛了`, tags: ["脏话", "吹牛", "动物世界"] },
    { author: tea('叶子'), content: `头转一转 哎呀 旁边那几个傻逼也没做出来 大家都一样`, tags: ["脏话"] },
    { author: tea('高子'), content: `又没真的说大腿粗，那你们都攀附${tea('叶子')}老师去（抱大腿）`, tags: ["外貌身材"] },
    { author: tea('邓子'), content: `你身上背钱了，今晚抢劫你`, tags: ["日常"] },
    { author: tea('高子'), content: `以后中国婚姻制度变了，女的娶一个男的回来`, tags: ["日常"] },
    { author: tea('高子'), content: `我喜欢这个，和这个……噢，是的，这个是有点帅。那我喜欢这个，这个和这个，我是颜控`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `那我以后看你找个丑的对象`, tags: ["外貌身材", "感情八卦"] },
    { author: tea('陈子三号'), content: `差点听成康洲城带着${stu(1, 28)}去马尔代夫`, tags: ["日常"] },
    { author: tea('叶子'), content: `老子今天猜中上海中考卷了！`, tags: ["日常"] },
    { author: tea('邓子'), content: `他居然想找个帅老公？`, tags: ["外貌身材", "感情八卦"] },
    { author: tea('叶子'), content: `读书屎，屎读书，读屎书。`, tags: ["屎尿屁"] },
    { author: tea('叶子'), content: `早死早超生`, tags: ["日常"] },
    { author: tea('高子'), content: `男生跑得快 因为男生有三条腿`, tags: ["开车"] },
    { author: tea('高子'), content: `一等初三毕业之后，我就回来干掉你（等你回来干掉我）`, tags: ["日常"] },
    // 12
    { author: tea('高子'), content: `布了布了布了布了（ble ble ble ble）`, tags: ["日常"] },
    { author: tea('高子'), content: `作(zuō)作(zuō)的！`, tags: ["日常"] },
    { author: tea('叶子'), content: `你（康洲城）是0我是1`, tags: ["开车"] },
    { author: tea('高子'), content: `来查我 你们查完我 我就（开始）查你们了`, tags: ["日常"] },
    { author: tea('叶子'), content: `你现在变成自爆卡车啦`, tags: ["日常"] },
    { author: tea('高子'), content: `你（${stu(2, 21)}）手真好玩`, tags: ["日常"] },
    { author: tea('叶子'), content: `带分数去死掉`, tags: ["暴言", "作业考试"] },
    { author: tea('叶子'), content: `$\\pi$和$\\dfrac{22}7$他娘的什么关系都没有`, tags: ["脏话", "学科"] },
    { author: tea('叶子'), content: `好了，你（${tea('叶子')}的数学老师）今天死掉（超重音）了！`, tags: ["暴言", "学科"] },
    { author: tea('叶子'), content: `哇什么情况`, tags: ["日常"] },
    { author: tea('余子'), content: `我们班谁是拉`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 1)} 你头太大了是吧`, tags: ["日常"] },
    { author: tea('高子'), content: `哎哟喂！谁的声音这么娇嫩啊（${stu(2, 15)}）`, tags: ["日常"] },
    { author: tea('叶子'), content: `出卷可以让你们死得很爽`, tags: ["日常"] },
    { author: tea('邓子'), content: `成功执行枪毙3次！`, tags: ["暴言"] },
    { author: tea('邓子'), content: `我不会原谅你的`, tags: ["日常"] },
    { author: tea('邓子'), content: `你今天左脚进门被我扇了一巴掌那你得到的启示是什么`, tags: ["日常"] },
    // 13
    { author: tea('邓子'), content: `这俩小孩还不如生一个叉烧`, tags: ["日常"] },
    { author: tea('邓子'), content: `要是不把这俩小孩踹飞都是那俩小孩不够轻`, tags: ["日常"] },
    { author: tea('高子'), content: `我要是有江山 肯定不止两个男宠`, tags: ["开车"] },
    { author: tea('叶子'), content: `我女儿智商不是特别高 我觉得`, tags: ["日常"] },
    { author: tea('叶子'), content: `我欠5块钱 你欠6块钱 谁钱多`, tags: ["日常"] },
    { author: tea('高子'), content: `天若有情天亦老，人若多情死得早。`, tags: ["日常"] },
    { author: tea('高子'), content: `待会到记叙文就炸了！`, tags: ["日常"] },
    { author: tea('高子'), content: `哦！原来如此！`, tags: ["日常"] },
    { author: tea('高子'), content: `我不要面包 我要百香果`, tags: ["日常"] },
    { author: tea('叶子'), content: `吃屎要吃热乎的。`, tags: ["屎尿屁", "吃的"] },
    { author: tea('叶子'), content: `你只能去适应规则，不能去打破规则。`, tags: ["日常"] },
    { author: tea('叶子'), content: `我这个老革命遇到新难题了喽？`, tags: ["日常"] },
    { author: tea('叶子'), content: `像XXX、XXX这种，坐的时候下巴是在桌子上的，屁股离桌子老远，身体还要抖，屁股还要摇`, tags: ["开车", "屎尿屁"] },
    { author: tea('叶子'), content: `我教你们班，真是荣幸啊`, tags: ["日常"] },
    // 14
    { author: tea('叶子'), content: `一个欣竹陶喆（${stu(1, 9)}），一个欣竹周杰伦（${stu(1, 17)}）`, tags: ["名人梗"] },
    { author: tea('高子'), content: `（${stu(2, 16)}）在自己的笔袋里深海探索。`, tags: ["日常"] },
    { author: tea('高子'), content: `六个人（蛟龙号和神舟九号上的人）咋不带上我嘞？`, tags: ["日常"] },
    { author: tea('高子'), content: `联合国会议可以不带我，但讨伐${stu(2, 1)}一定要带上我噢`, tags: ["日常"] },
    { author: tea('邓子'), content: `我还不如去摇奶茶`, tags: ["吃的"] },
    { author: tea('邓子'), content: `我以前还有个学生给我花大□`, tags: ["日常"] },
    { author: tea('邓子'), content: `去学校门口当保安`, tags: ["日常"] },
    { author: tea('高子'), content: `别解释，解释就三联单`, tags: ["日常"] },
    { author: tea('许子'), content: `再搞就把桌子舔干净`, tags: ["日常"] },
    { author: tea('许子'), content: `挖鼻屎的（${stu(2, 10)}）来拿你卷子`, tags: ["屎尿屁", "作业考试"] },
    { author: tea('许子'), content: `你挖完鼻屎（还）把手伸到嘴巴里`, tags: ["屎尿屁"] },
    { author: tea('许子'), content: `挖完鼻屎挖牙齿`, tags: ["屎尿屁"] },
    { author: tea('许子'), content: `动人家头干什么`, tags: ["日常"] },
    { author: tea('余子'), content: `还有那个蔬菜啥 蔬菜人`, tags: ["吃的"] },
    { author: tea('余子'), content: `谁？谁？啥？嗯。啊？`, tags: ["日常"] },
    { author: tea('余子'), content: `<img src="cry.png" alt="哭脸" style="height:2.8em;vertical-align:middle;">`, tags: ["日常"] },
    // 15
    { author: tea('余子'), content: `你根呢`, tags: ["日常"] },
    { author: tea('余子'), content: `啊啊啊（恶龙咆哮）屎后面去□□去`, tags: ["屎尿屁"] },
    { author: tea('余子'), content: `工厂化养殖的……肯德基。`, tags: ["日常"] },
    { author: tea('邓子'), content: `这个□审美提高`, tags: ["日常"] },
    { author: tea('陈子一号'), content: `四个小钢炮，还有个原子弹`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 3)}，记得好好复习，这学期成绩好像没有那么拔尖了哦~（此时${stu(2, 3)}不在教室）`, tags: ["作业考试", "班级纪律"] },
    { author: tea('高子'), content: `你们可以抢他的呀，现在${stu(2, 3)}不在教室里我跟你们□`, tags: ["班级纪律"] },
    { author: tea('高子'), content: `在陆家嘴（这一块）放一个炸弹死多以`, tags: ["日常"] },
    { author: tea('高子'), content: `一个人跟斗眼鸡一样，你斗我，我斗你`, tags: ["动物世界"] },
    { author: tea('高子'), content: `有一个基金叫葛兰的，我还买了好多，亏了好多`, tags: ["日常"] },
    { author: tea('高子'), content: `好像我挂了十几万块钱，现在亏了有四万了`, tags: ["日常"] },
    { author: tea('高子'), content: `这种风雅之事的境界我也达不到，因为我要做班主任`, tags: ["日常"] },
    { author: tea('高子'), content: `把你那卷毛全都剃掉装我头上`, tags: ["日常"] },
    { author: tea('高子'), content: `你要是把你那卷毛做成假发送给我，我保证明天就戴上`, tags: ["日常"] },
    // 16
    { author: tea('高子'), content: `哪有你那么自残的嘞`, tags: ["日常"] },
    { author: tea('高子'), content: `让你做眼操没让你做头发操，你抓你头发干嘛`, tags: ["日常"] },
    { author: tea('高子'), content: `每次都是睡觉、跑步、放`, tags: ["日常"] },
    { author: tea('邓子'), content: `你们在这说话我都不敢听`, tags: ["日常"] },
    { author: tea('刘子二号'), content: `同桌之间交通一下`, tags: ["日常"] },
    { author: tea('叶子'), content: `流鼻血啦，早上吃啥了这么补呀，还是我的课太恶心啦`, tags: ["吃的"] },
    { author: tea('叶子'), content: `好了，今天我没有时间陪你们扯淡`, tags: ["日常"] },
    { author: tea('余子'), content: `这上面的几几写了吧`, tags: ["日常"] },
    { author: tea('余子'), content: `口水吐不出□羊来`, tags: ["日常"] },
    { author: tea('许子'), content: `你这个挖鼻屎的手不想让你碰我的卷子`, tags: ["屎尿屁", "作业考试"] },
    { author: tea('许子'), content: `你是在用屁股动它`, tags: ["开车", "屎尿屁"] },
    { author: tea('刘子'), content: `我造了一只狗，这就是实例`, tags: ["动物世界"] },
    { author: tea('许子'), content: `现在不说话了，非得用身体上什么别的部位发出些什么声音是吧`, tags: ["日常"] },
    { author: tea('许子'), content: `${stu(2, 10)}改成施宝宝`, tags: ["日常"] },
    { author: tea('邓子'), content: `你们看97页上面这个小胖子（明神宗）`, tags: ["外貌身材"] },
    { author: tea('叶子'), content: `没所谓`, tags: ["日常"] },
    { author: tea('邓子'), content: `你听那个废话`, tags: ["日常"] },
    // 17
    { author: tea('邓子'), content: `最喜欢干这种缺德的事的了`, tags: ["日常"] },
    { author: tea('邓子'), content: `你说什么（气音）（低沉）（撕心裂肺）`, tags: ["日常"] },
    { author: tea('邓子'), content: `骑过新华门的时候定要不注意撇一撇头，看一眼那个执勤小哥，那个执勤小哥有东西`, tags: ["日常"] },
    { author: tea('余子'), content: `把你们安安全全送走`, tags: ["日常"] },
    { author: tea('余子'), content: `如果哪天你们看不到我和B班的那就是抽中彩票了`, tags: ["日常"] },
    { author: tea('余子'), content: `真想买块豆腐`, tags: ["日常"] },
    { author: tea('许子'), content: `有些同学写牲畜业，幸好没写畜牲（畜生）业`, tags: ["日常"] },
    { author: tea('高子'), content: `好，终于求我了`, tags: ["日常"] },
    { author: tea('高子'), content: `你把我气笑了`, tags: ["日常"] },
    { author: tea('高子'), content: `你还不如混江湖去`, tags: ["日常"] },
    { author: tea('高子'), content: `如果${stu(2, 10)}混江湖去了，那${stu(2, 12)}就是跟在后面抗□□的`, tags: ["日常"] },
    { author: tea('高子'), content: `来，这个干架的状态准备`, tags: ["日常"] },
    { author: tea('高子'), content: `去抓一个肥美的鹿回来`, tags: ["外貌身材"] },
    { author: tea('高子'), content: `阳光玫瑰不好吃`, tags: ["吃的"] },
    { author: tea('高子'), content: `你再讲话我就想把拖鞋拔下来抽你`, tags: ["脏话"] },
    { author: tea('高子'), content: `（1班上心理）简直就跟${stu(2, 24)}大叫起来一样`, tags: ["日常"] },
    // 18
    { author: tea('宁子'), content: `三联单争夺战`, tags: ["日常"] },
    { author: tea('宁子'), content: `猜定拳，谁输了谁得三联单`, tags: ["日常"] },
    { author: tea('余子'), content: `你（${stu(2, 37)}）要不要放学后去我办公室锻炼一下抄的速度`, tags: ["日常"] }, // 编者加
    { author: tea('余子'), content: `你们三个坨在一起`, tags: ["日常"] }, // 编者加
    { author: tea('高子'), content: `像这样（身体前倾，手腕上下摆），像这样（身体前倾，手腕上下摆），像这样（身体前倾，手腕上下摆）`, tags: ["日常"] },
    { author: tea('高子'), content: `亲爱的老师（后仰踢腿），亲爱的同学们（后仰踢腿），大家好（后仰踢腿）`, tags: ["日常"] },
    { author: tea('高子'), content: `二胡（${stu(2, 7)}、${stu(2, 24)}）一张（${stu(2, 37)}）一熊（${stu(2, 15)}）`, tags: ["日常"] }, // 编者加
    { author: tea('叶子'), content: `一班说篮球也就算了，你们班我就没见过几个打篮球的`, tags: ["日常"] },
    { author: tea('叶子'), content: `我要开始发神经病啦`, tags: ["脏话"] },
    { author: tea('叶子'), content: `我的神经病都是从你们这学的哦`, tags: ["脏话"] },
    { author: tea('高子'), content: `吃得爽`, tags: ["吃的"] },
    { author: tea('高子'), content: `哪个娇滴滴的宝宝要抱呀`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `（${stu(1, 9)}）还要唱着问我问题`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `来，大红袍先生（${stu(2, 2)}）`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `乖乖(guài)`, tags: ["日常"] },
    // 19
    { author: tea('陈子三号'), content: `你们去问隔壁${stu(1, 9)}借点自信，或者找${stu(1, 17)}`, tags: ["日常"] },
    { author: stu(1, 9), content: `肯定是你（${tea('陈子三号')}）批错了`, tags: ["作业考试"] },
    { author: tea('陈子三号'), content: `把同学们从操场上抱起来，然后扔到操场外面去`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `长焦镜头就大炮`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `你牙齿咋还反光呢`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `你（某位自管会）几班的啊，我好像见过你`, tags: ["日常"] },
    { author: "自管会", content: `老师（${tea('陈子三号')}）我也见过你`, tags: ["日常"] },
    { author: tea('陈子三号'), content: `你（${stu(2, 23)}）是小八嘎`, tags: ["日常"] },
    { author: tea('邓子'), content: `那我不知道呀`, tags: ["日常"] },
    { author: tea('邓子'), content: `假设你现在在外网和一个支持台独的吵架`, tags: ["日常"] },
    { author: tea('邓子'), content: `马上来逮你`, tags: ["日常"] },
    { author: tea('邓子'), content: `${stu(2, 1)}你根本没有做到知行合一`, tags: ["日常"] },
    // 20
    { author: tea('欧阳子'), content: `This is what?`, tags: ["日常"] }, // 编者加
    { author: tea('欧阳子'), content: `Let me see your branches!（指fingers）`, tags: ["日常"] }, // 编者加
    { author: tea('欧阳子'), content: `What do you do?`, tags: ["日常"] },
    { author: tea('欧阳子'), content: `Great!×n Good!×n Very good!×n`, tags: ["日常"] },
    { author: tea('叶子'), content: `你们（课后服务一、二班同学）坐着干嘛，快夸我（作业布置得少）啊！`, tags: ["作业考试"] }, // 编者加
    { author: tea('叶子'), content: `明天，早上，8点钟以前，（${stu(1, 9)}、${stu(1, 2)}）不要在我眼前出现`, tags: ["日常"] }, // 编者加
    { author: tea('叶子'), content: `你说，像这两个傻屌（${stu(1, 9)}、${stu(1, 2)}）`, tags: ["脏话"] }, // 编者加
    { author: tea('余子'), content: `我马上要没时间了啊（此时距下课还有20几分钟）`, tags: ["日常"] },
    { author: tea('余子'), content: `待会儿你要自己一个人留下来在小黑屋里写啦`, tags: ["日常"] },
    { author: tea('叶子'), content: `我要忍不住了`, tags: ["日常"] },
    { author: tea('高子'), content: `今天陈大厨（${stu(2, 1)}）来给我们做一道乌鸦炸酱面`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 12)}是个可爱的开朗的小孩子`, tags: ["日常"] },
    { author: tea('邓子'), content: `公开批判你`, tags: ["日常"] },
    { author: tea('邓子'), content: `哭什么哭，哭什么哭（尖叫）（扯嗓子）（撕心裂肺）`, tags: ["日常"] },
    { author: tea('邓子'), content: `（七2班第一学期）简直就是没开智`, tags: ["日常"] },
    { author: tea('邓子'), content: `把虫子炒一炒吃了，生吞也行`, tags: ["动物世界", "吃的"] },
    { author: tea('高子'), content: `你俩要亲一个吗（${stu(2, 1)}&${stu(2, 10)}）`, tags: ["日常"] },
    { author: tea('邓子'), content: `三国霸主齐桓公`, tags: ["日常"] },
    { author: tea('高子'), content: `把他无了`, tags: ["日常"] },
    { author: stu(2, 21), content: `桂林不是山东省的吗`, tags: ["日常"] },
    { author: tea('宁子'), content: `想把你的脑袋拧下来当球踢`, tags: ["日常"] },





    // 心形纸
    { author: tea('高子'), content: `我现在腿有点慢（使劲踹某人的书包）`, tags: ["日常"] },
    { author: tea('高子'), content: `${stu(2, 1)}的物理成绩跟我差不多`, tags: ["作业考试", "学科"] },
    { author: tea('高子'), content: `好多蚂蚁在我脑子里面`, tags: ["日常"] },
    { author: tea('高子'), content: `用你的脑子抓一只□□回去给你爸妈`, tags: ["日常"] },
    { author: tea('高子'), content: `我再也不管你们了`, tags: ["日常"] },





    // 第三册
    // 1
    { author: tea('余子'), content: `马上要毕业了`, tags: ["日常"] },
    { author: tea('高子'), content: `我就希望咱们班能有两个人考上进才的`, tags: ["日常"] },
    { author: tea('王校长'), content: `亲爱的……啊`, tags: ["日常"] },
    { author: "丁副校长", content: `老师……啊`, tags: ["日常"] },
    { author: "丁副校长", content: `要要要要要要`, tags: ["日常"] },
    { author: tea('叶子'), content: `当时我讲的时候我就在想：老子真牛逼，然后后来那个听课的老师也觉得我讲得好。但我不是听那个老师说才觉得好的，我在写教案的时候就觉得老子写的真精（美），比课本都好。`, tags: ["吹牛", "班级纪律", "动物世界"] },
    { author: "王子？号", content: `一年多十几个月`, tags: ["日常"] },
    { author: tea('孙子'), content: `2班这么高级，哎哟喂，你们班还很高级`, tags: ["日常"] },
    { author: tea('孙子'), content: `你头这么重，连脖子都撑不住`, tags: ["日常"] },
    // 2
    { author: tea('邓子'), content: `上个学期干得不错，这学期继续精进`, tags: ["日常"] },
    { author: tea('邓子'), content: `坐太久屁股就死了`, tags: ["开车", "屎尿屁"] },
    { author: tea('邓子'), content: `做（操）得还没有老年人撞树声音大`, tags: ["日常"] },
    { author: tea('孙子'), content: `先结婚再恋爱`, tags: ["感情八卦"] },
    { author: tea('孙子'), content: `好吧？↗`, tags: ["日常"] },
    { author: tea('高子'), content: `你们的屁股是值钱的`, tags: ["开车", "屎尿屁"] },
    { author: tea('高子'), content: `（向天微摇头）我没听到`, tags: ["日常"] },
    { author: stu(2, 10), content: `靠卖屁股（<${tea('高子')}>很久以前说“你我这样的人也有办法过下去”）`, tags: ["开车", "屎尿屁"] },
    { author: tea('高子'), content: `抱一下`, tags: ["日常"] },
    { author: stu(2, 10), content: `要抱就抱最轻的${stu(2, 18)}`, tags: ["日常"] }, // 原文于第3页第3句，按顺序应在第2页此处
    { author: tea('孙子'), content: `小可爱（${stu(2, 16)}），来`, tags: ["日常"] },
    { author: tea('孙子'), content: `不要上物理课的时候玩啊，你（${stu(2, 16)}）要练练别被抓到`, tags: ["学科"] },
    // 3
    { author: tea('孙子'), content: `你别说这还挺好玩的`, tags: ["日常"] },
    { author: tea('孙子'), content: `你不喜欢我上的课吗？喜不喜欢？`, tags: ["日常"] },
    { author: tea('高子'), content: `抱叶老师？那得……那不得几个人围在一起（双手打开）抱`, tags: ["日常"] },
    { author: tea('郎子'), content: `我需要一个人替我记死亡笔记`, tags: ["名人梗"] },
    {
        author: tea('郎子'),
        content: `琪琪（${stu(2, 37)}）偷偷喜欢上了小花花（${stu(2, 12)}），他是一个负责任的男人，他想在小花花的生日给他送一个礼物，这时候琪琪的室友好兄弟胡哥们儿（${stu(2, 24)}）听到小花花的朋友大美（${stu(2, 5)}）说小花花想要一条2000的项链，于是胡哥们儿就把这件情报` +
                 `卖给了琪琪（琪琪在清华大学）。`, // 本行原文于第4页第1行，按顺序应在第3页此处
        tags: ["琪琪与小花花"]
    },
    // 4
    {
        author: tea('郎子'),
        content: `后来琪琪终于买到了项链，然后在圣诞节那一天，琪琪向小花花表达了自己的心意。当然，这基本也少不了胡哥们儿的帮助。好，小花花你愿意吗？（${stu(2, 12)}没说话）啊，你愿意啊`,
        tags: ["琪琪与小花花"]
    },
    { author: tea('殷子'), content: `为了我们在学校里的幸福生活`, tags: ["日常"] },
    { author: tea('殷子'), content: `上车睡觉下车尿尿`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `谁的衣服需要修理，我来问候一下他的屁股`, tags: ["开车", "屎尿屁"] },
    { author: tea('叶子'), content: `hihihihihihihi（□的□调）`, tags: ["日常"] },
    { author: tea('叶子'), content: `下次继续（黄靖远告诉${stu(1, 1)}错误的作业）`, tags: ["作业考试"] },
    { author: tea('叶子'), content: `我叫门捷叶夫好吧，元素周期表是我发明的`, tags: ["学科", "名人梗"] },
    { author: tea('叶子'), content: `你们的一生之敌（$\\sqrt{8}$）又来啦`, tags: ["学科"] },
    { author: tea('叶子'), content: `26这个数字也很好`, tags: ["日常"] },
    // 5
    { author: tea('叶子'), content: `什么时候让你领教一下浙江省一级重点中学的化学小天才`, tags: ["学科"] },
    { author: tea('孙子'), content: `你（${stu(2, 19)}）这个不负责任的男人`, tags: ["日常"] },
    { author: tea('高子'), content: `谁是你哥们儿，我是你大爷`, tags: ["日常"] },
    { author: tea('高子'), content: `我是你爷行了吧`, tags: ["日常"] },
    { author: tea('高子'), content: `不要来惹爷，爷脾气大得很`, tags: ["日常"] },
    { author: tea('高子'), content: `（仰头闭眼打呼）`, tags: ["日常"] },
    {
        author: tea('郎子'),
        content: `没有小花花，被他（琪琪）踹了`,
        tags: ["琪琪与小花花"]
    },
    {
        author: tea('郎子'),
        content: `现在琪琪已经硕士毕业了，然后他走了老路：上岸先斩意中人，因为小花花不愿意回上海`,
        tags: ["琪琪与小花花"]
    },
    { author: tea('郎子'), content: `没情商的玩意儿`, tags: ["日常"] },
    // 6
    {
        author: tea('郎子'),
        content: `那么也就是说如果琪琪这时候入了新单位，然后在入职那天发现工位的对面坐着一位温柔的眼睛妹妹（对着${stu(2, 4)}）（大喘气）的话`,
        tags: ["琪琪与小花花"]
    },
    {
        author: tea('郎子'),
        content: `（对${stu(2, 4)}说）唉干嘛没说你，这说你夸你好看呢，你看人家嘉琪多大方`,
        tags: ["琪琪与小花花"]
    },
    { author: tea('郎子'), content: `舔狗都不得好死`, tags: ["脏话", "动物世界"] },
    { author: tea('郎子'), content: `（问${stu(2, 37)}）你是舔狗嘛`, tags: ["脏话", "动物世界"] },
    { author: tea('叶子'), content: `我一年十万，被你们气一下就少活十年，以后等你们毕业了就写一本书，就叫《我是如何杀死百万富翁的》`, tags: ["暴言", "吹牛"] },
    // 7
    { author: tea('叶子'), content: `可惜我们学校已经被推倒啦，之前想挖一个车库，结果挖到6000年以前的古城了，还入选2025十大考古发现了呢`, tags: ["吹牛"] },
    { author: tea('叶子'), content: `不告诉你，让你晚上睡不着`, tags: ["日常"] },
    { author: tea('叶子'), content: `我家以前是住古玩市场的，然后我□□了上海博物馆就出不来啦，这个也好那个也好`, tags: ["日常"] },
    { author: tea('武子'), content: `（对${stu(2, 24)}说）就你扫`, tags: ["日常"] },
    { author: tea('叶子'), content: `你要是考100，我用显微镜把你的卷子从头到尾看一遍`, tags: ["作业考试"] },
    { author: tea('高子'), content: `我感觉到我腿上有水，谁在喷水`, tags: ["日常"] },
    { author: tea('武子'), content: `（对${stu(2, 10)}说）坐月子啊`, tags: ["日常"] },
    { author: tea('邓子'), content: `我兜里有一把枪，掏出来把你削掉`, tags: ["日常"] },
    { author: tea('叶子'), content: `hi↷hi↷hi↷`, tags: ["日常"] },
    // 8
    { author: tea('邓子'), content: `你们怎么都死死的`, tags: ["暴言"] },
    { author: tea('郎子'), content: `他（${tea('郎子')}的好兄弟）大概是叶老师的$\\dfrac{1}{3}$`, tags: ["学科"] },
    { author: tea('郎子'), content: `傻叉`, tags: ["脏话"] },
    { author: tea('郎子'), content: `这是一个番茄（${stu(2, 16)}）`, tags: ["吃的"] },
    { author: tea('高子'), content: `哎哟我好怕你们哟，我怕的我马上就要走了(?)`, tags: ["日常"] },
    { author: tea('叶子'), content: `他娘的还要花一节课来讲这个傻屌题目`, tags: ["脏话"] },
    { author: tea('叶子'), content: `唉？陶喆（${stu(1, 9)}）咋没进十佳歌手啊`, tags: ["名人梗"] },
    { author: tea('叶子'), content: `哪个评委这么没眼光，陶喆的歌不选`, tags: ["名人梗"] },
    { author: tea('叶子'), content: `我唱歌要我给别人钱`, tags: ["日常"] },
    { author: tea('毕子'), content: `好不好吃(?)`, tags: ["吃的"] },
    // 9
    { author: tea('陈子一号'), content: `我可是昨天下午花了两个小时想出来的（一页PPT）`, tags: ["日常"] },
    { author: tea('陈子一号'), content: `拿出我的尚方宝剑（一根？条子放在脸中间）`, tags: ["日常"] },
    { author: tea('孙子'), content: `写得跟一坨便便一样的`, tags: ["屎尿屁"] },
    { author: tea('武子'), content: `SB，说的就是你（${stu(2, 10)}）`, tags: ["脏话"] },
    { author: tea('武子'), content: `${stu(2, 10)}，我草你妈`, tags: ["脏话"] },
    { author: tea('高子'), content: `你找个男朋友还是女朋友我都□□□你们□□`, tags: ["感情八卦"] },
    { author: tea('高子'), content: `你是拉还是gay`, tags: ["开车"] },
    { author: stu(2, 37), content: `老师你是给吗`, tags: ["日常"] },
    { author: tea('高子'), content: `（回答）我不是`, tags: ["日常"] },
    { author: tea('高子'), content: `忙完你的忙你的，忙完你的忙他的`, tags: ["日常"] },
    { author: tea('高子'), content: `我当年物理□□考了□□□`, tags: ["学科", "吹牛"] },
    // 10
    { author: tea('高子'), content: `我祝你不拉屎`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `那不行，我得拉`, tags: ["日常"] },
    { author: tea('高子'), content: `哦↝`, tags: ["日常"] },
    { author: tea('高子'), content: `你们这里谁（去）拉屎了吗`, tags: ["屎尿屁"] },
    { author: tea('高子'), content: `啊，这个人真好看`, tags: ["外貌身材"] },
];
